%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Alexandr\Documents\Source\Repos\Lab3\MassiveDots.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/11/05 21:56:04

%% Initialize variables.
filename = 'C:\Users\Alexandr\Documents\Source\Repos\Lab3\MassiveDots.txt';
delimiter = ' ';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
MassiveDots1 = table(dataArray{1:end-1}, 'VariableNames', {'VarName1','VarName2'});

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;
% plot(MassiveDots.VarName1,MassiveDots.VarName2);
% hold;

%% func1
%x = linspace(-1.0,1.0);
% %y=x;
%y=x.*x;
%% func2
%x = linspace(-1.0,1.0);
%y=1./(1+10*x.*x);
    %% func3
 %x = linspace(-3.0,3.0);
 %y=1./atan(1+10*x.*x);
%% func4
 x = linspace(-1.0,1.0);
 h = 4 * x.*x.*x + 2 * x.*x - 4 * x + 2;
 g=asin(1./(5+x-x.*x));
 y=h.^sqrt(2) + g - 5;
% double h = 4 * x*x*x + 2 * x*x - 4 * x + 2;
% 	double g = asin(1/(5+x-x*x));
% 	 
% 	return (pow(h, sqrt(2)) + g - 5);
 %% func5
%x = linspace(0.0,2.0);
%y=exp(x);

 plot(x,y,MassiveDots1.VarName1,MassiveDots1.VarName2);
%  ,'gs',...
%     'LineWidth',2,...
%     'MarkerSize',2,...
%     'MarkerEdgeColor','b',...
%     'MarkerFaceColor',[0.5,0.5,0.5]);%'go'